name: example
description: Envied example
version: 2.0.2
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  envied: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
  build_runner: ^2.4.13
  envied_generator: 
    path: ../../packages/envied_generator

dependency_overrides: 
  envied:
    path: ../../packages/envied